---
language: node_js
node_js:
  - "4"

sudo: false

addons:
  code_climate:
    repo_token: f8dc665e9c00b1004c7096875601a3bb39b6b8afd640ca63bca0255068403d35

cache:
  directories:
    - node_modules

before_install:
  - npm config set spin false
  - npm install -g bower
  - npm install phantomjs-prebuilt

install:
  - npm install
  - bower install

script:
  - ember test

after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < lcov.info
